# Generated by Django 3.2 on 2021-12-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_auto_20211208_1406"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
