services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfiles/movies_admin/Dockerfile
      target: development
    working_dir: /src/movies_admin
    command: ["gunicorn"  , "--bind", "0.0.0.0:8000", "config.wsgi"]
    environment:
      - DEBUG=False
    volumes:
      - "./movies_admin:/src/movies_admin"
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres:13.0-alpine
    volumes:
      - admin_postgres:/var/lib/postgresql/data/
      - ./Configs/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    restart: always

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - ./movies_admin/staticfiles:/home/movies_admin/staticfiles
    depends_on:
      - web
    ports:
      - "80:80"
volumes:
  admin_postgres:
    driver: 'local'
