services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfiles/movies_admin/Dockerfile
      target: development
    working_dir: /src/movies_admin
    command: ["python"  , "manage.py" ,"runserver","0.0.0.0:8000"]
    environment:
      - DEBUG=True
    volumes:
      - "./movies_admin:/src/movies_admin"
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres:13.0-alpine
    volumes:
      - admin_postgres:/var/lib/postgresql/data/
      - ./Configs/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    restart: always

volumes:
  admin_postgres:
    driver: 'local'
