# Generated by Django 3.2 on 2021-12-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwork',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='filmwork',
            name='persons',
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
